/**
 * GOOGLE AI GATEWAY v1.0 - Gemini API Abstraction Layer
 * 
 * Drop-in replacement for Base44 InvokeLLM calls using Google Gemini API.
 * Designed for easy migration: same input/output contract as InvokeLLM.
 * 
 * Supports:
 * - Text generation with configurable temperature
 * - JSON schema responses (structured output)
 * - File/image URL analysis (vision)
 * - Web search grounding (Google Search)
 * 
 * Endpoint: POST /googleAI
 * Payload: { prompt, temperature?, response_json_schema?, file_urls?, add_context_from_internet? }
 * Returns: { success, result, provider, model, usage? }
 * 
 * CHANGELOG:
 * v1.0 - Initial implementation with Gemini 2.0 Flash
 */

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const GOOGLE_AI_API_KEY = Deno.env.get('GOOGLE_AI_API_KEY');
const GEMINI_MODEL = 'gemini-2.0-flash';
const GEMINI_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * Convert file URLs to Gemini-compatible inline data parts.
 * Fetches each URL and encodes as base64 for the Gemini vision API.
 * @param {string[]} fileUrls - Array of image/file URLs
 * @returns {Promise<object[]>} Array of Gemini content parts
 */
async function buildFileParts(fileUrls) {
    const parts = [];
    for (const url of fileUrls) {
        try {
            const response = await fetch(url);
            const buffer = await response.arrayBuffer();
            const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));
            const contentType = response.headers.get('content-type') || 'image/jpeg';
            parts.push({
                inline_data: {
                    mime_type: contentType,
                    data: base64
                }
            });
        } catch (e) {
            console.warn(`[GoogleAI] Failed to fetch file ${url}: ${e.message}`);
        }
    }
    return parts;
}

/**
 * Call Google Gemini API directly.
 * Mirrors the InvokeLLM interface for drop-in compatibility.
 * 
 * @param {object} params
 * @param {string} params.prompt - The text prompt
 * @param {number} [params.temperature=0.7] - Generation temperature
 * @param {object} [params.response_json_schema] - Optional JSON schema for structured output
 * @param {string[]} [params.file_urls] - Optional file/image URLs for vision
 * @param {boolean} [params.add_context_from_internet] - Enable Google Search grounding
 * @returns {Promise<string|object>} Text response or parsed JSON object
 */
async function callGemini({ prompt, temperature = 0.7, response_json_schema, file_urls, add_context_from_internet }) {
    if (!GOOGLE_AI_API_KEY) {
        throw new Error('GOOGLE_AI_API_KEY not configured');
    }

    // Build content parts
    const parts = [{ text: prompt }];

    // Add vision parts if file_urls provided
    if (file_urls && file_urls.length > 0) {
        const fileParts = await buildFileParts(file_urls);
        parts.push(...fileParts);
    }

    // Build request body
    const requestBody = {
        contents: [{ parts }],
        generationConfig: {
            temperature,
            maxOutputTokens: 8192
        }
    };

    // Add JSON response format if schema provided
    if (response_json_schema) {
        requestBody.generationConfig.responseMimeType = 'application/json';
        requestBody.generationConfig.responseSchema = response_json_schema;
    }

    // Add Google Search grounding if requested
    if (add_context_from_internet) {
        requestBody.tools = [{ google_search: {} }];
    }

    // Make API call
    const endpoint = `${GEMINI_BASE_URL}/${GEMINI_MODEL}:generateContent?key=${GOOGLE_AI_API_KEY}`;

    const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
        const errorBody = await response.text();
        throw new Error(`Gemini API error (${response.status}): ${errorBody}`);
    }

    const data = await response.json();

    // Extract text from response
    const candidate = data.candidates?.[0];
    if (!candidate || !candidate.content?.parts?.[0]) {
        throw new Error('No response generated by Gemini');
    }

    const textResult = candidate.content.parts[0].text;

    // Parse JSON if schema was requested
    if (response_json_schema) {
        try {
            return JSON.parse(textResult);
        } catch {
            return textResult;
        }
    }

    return textResult;
}

// HTTP Handler - exposes callGemini as a backend function
Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();
        if (!user) {
            return Response.json({ error: 'Unauthorized', success: false }, { status: 401 });
        }

        const payload = await req.json();
        const { prompt, temperature, response_json_schema, file_urls, add_context_from_internet } = payload;

        if (!prompt) {
            return Response.json({ error: 'prompt is required', success: false }, { status: 400 });
        }

        const result = await callGemini({
            prompt,
            temperature,
            response_json_schema,
            file_urls,
            add_context_from_internet
        });

        return Response.json({
            success: true,
            result,
            provider: 'google',
            model: GEMINI_MODEL
        });

    } catch (error) {
        console.error('[GoogleAI] Error:', error.message);
        return Response.json({
            success: false,
            error: error.message
        }, { status: 500 });
    }
});